export type InspirationCase = {
  id: string;
  category: string;
  style: string;
  colors: { base: string; print: string; aux: string; raw: string };
  tags: string[];
  sizes: string[];
  promptJson: string;
  imageUrl: string;
};

export const INSPIRATION_CASES: InspirationCase[] = [
  {
    id: 'case-13',
    category: "校外商家需求",
    style: "蛋糕店：日系甜美",
    colors: {
      base: "白",
      print: "深蓝色印花",
      aux: "橙",
      raw: "",
    },
    tags: ["日系", "可爱", "甜美", "简约"],
    sizes: ["正面占50%～60%，左肩袖子较小"],
    promptJson: "{\n  \"tshirt_design\": {\n    \"style_type\": \"日系简约可爱风\",\n    \"colors\": {\n      \"base_color\": \"米白色/纯白色\",\n      \"print_colors\": [\n        \"深蓝色/藏青色\",\n        \"橙色/橘红色\"\n      ]\n    },\n    \"pattern_positions\": {\n      \"front\": {\n        \"location\": \"正中央（胸部至腹部上方区域）\",\n        \"description\": \"完整的“今亦甜”卡通形象Logo\",\n        \"size_ratio\": \"占正面视觉面积的50%-60%\"\n      },\n      \"sleeve\": {\n        \"location\": \"左肩袖子区域\",\n        \"description\": \"缩小版的Logo作为辅助装饰\",\n        \"size_ratio\": \"约为主图案的1/4到1/5\"\n      }\n    }\n  }\n}",
    imageUrl: "/images/case-13.png",
  },
  {
    id: 'case-10',
    category: "学校比赛/期末提案需求",
    style: "参加比赛：专业干练风格",
    colors: {
      base: "白",
      print: "绿白",
      aux: "红蓝",
      raw: "",
    },
    tags: ["团队", "可靠", "有准备"],
    sizes: ["仅正面左胸口处5～8cm"],
    promptJson: "\"tshirt_design\": {\n     \"style_type\": \"专业干练风格（比赛用）\",\n     \"colors\": {\n       \"base_color\": \"纯白色\",\n       \"print_colors\": [\"绿色\", \"白色\", \"黄色\", \"红色\", \"蓝色\"]\n     },\n     \"pattern_positions\": {\n       \"front\": {\n         \"location\": \"左胸口位置（距离领口下方约15cm处）\",\n         \"description\": \"完整的梨花主题LOGO（包含绿色叶片、白色花瓣、黄色花蕊、红蓝飘带元素）\",\n         \"size\": \"直径约5~8cm\"\n       }\n     },\n     \"tags\": [\"团队\", \"可靠\", \"有准备\", \"专业\", \"干练\"]\n   }\n }",
    imageUrl: "/images/case-10.png",
  },
  {
    id: 'case-11',
    category: "学校比赛/期末提案需求",
    style: "期末提案：简约利落风格",
    colors: {
      base: "白",
      print: "绿",
      aux: "",
      raw: "",
    },
    tags: ["休闲", "活力", "有记忆点"],
    sizes: [],
    promptJson: "{\n  \"tshirt_design\": {\n    \"style_type\": \"休闲简约风格（期末提案用）\",\n    \"colors\": {\n      \"base_color\": \"纯白色\",\n      \"print_colors\": [\"薄荷绿/浅荧光绿\"]\n    },\n    \"pattern_positions\": {\n      \"front\": {\n        \"location\": \"左胸口位置（距离领口下方约15cm处）\",\n        \"description\": \"完整的卡通小羊LOGO（线条轮廓为薄荷绿/浅荧光绿，内部为镂空设计，呈现慵懒闭眼的可爱神态）\",\n        \"size\": \"直径约5~8cm\"\n      }\n    },\n    \"tags\": [\"休闲\", \"活力\", \"有记忆点\", \"简约\", \"可爱\"]\n  }\n}",
    imageUrl: "/images/case-11.png",
  },
 {
    id: 'case-12',
    category: "校外商家需求",
    style: "健身房：运动休闲风（兼顾专业性和舒适感）",
    colors: {
      base: "",
      print: "",
      aux: "",
      raw: "",
    },
    tags: ["健身", "简约", "运动", "舒适"],
    sizes: ["正面8～10cm，背面25cm"],
    promptJson: "{\n  \"workout_tshirt_design\": {\n    \"style_type\": \"运动休闲风\",\n    \"colors\": {\n      \"base_color\": \"深海蓝/雾霾蓝\",\n      \"accent_colors\": [\n        \"亮橙色\",\n        \"荧光黄\",\n        \"白色\"\n      ],\n      \"auxiliary_color\": \"黑色\"\n    },\n    \"pattern_positions\": {\n      \"front\": {\n        \"location\": \"左胸位置（距离领口下方约15cm处）\",\n        \"content\": \"健身房品牌LOGO（精简版，线条化设计）叠加动态剪影图标（如举铁/瑜伽姿势）\",\n        \"size\": \"直径约8-10cm\"\n      },\n      \"back\": {\n        \"location\": \"背部中心区域（覆盖肩胛骨下方至腰部以上）\",\n        \"content\": \"大号艺术字体“COACH”（或中文“教练”），字母做立体切割设计，下方加品牌Slogan（如“Shape Your Strength”）\",\n        \"size\": \"字母高度约25-30cm，整体图案占比背部面积约60%\"\n      }\n    }\n  }\n}",
    imageUrl: "/images/case-12.jpg",
  },
  {
    id: 'case-04',
    category: "电商平台搜索",
    style: "明星粉丝定制",
    colors: {
      base: "黑色",
      print: "白色",
      aux: "灰色为主色（粉丝文化经典底色）",
      raw: "黑色、白色、灰色为主色（粉丝文化经典底色）；辅助色可用应援色",
    },
    tags: ["应援", "潮流", "个性", "社群文化"],
    sizes: ["胸前主图：25–30cm"],
    promptJson: "{\n  \"kpop_fan_tshirt_design\": {\n    \"style_type\": \"追星应援风\",\n    \"garment_type\": \"圆领短袖T恤\",\n    \"colors\": {\n      \"base_color\": \"纯白色\",\n      \"accent_colors\": [\n        \"黑色\",\n        \"亮黄色\",\n        \"紫色\",\n        \"红色\",\n        \"绿色\",\n        \"青色\",\n        \"蓝色\",\n        \"粉色\"\n      ],\n      \"auxiliary_color\": \"浅米色\"\n    },\n    \"pattern_positions\": {\n      \"front\": {\n        \"location\": \"胸前中心区域（覆盖领口下方至腹部上方）\",\n        \"content\": \"左侧为加粗黑色字母“I”，右侧为心形镂空框内嵌Jennie闭眼睡颜照片；下方为加粗圆润黑色字体“jennie”，字母“n”上叠加浅米色卡通小狗形象，右侧搭配白色天使翅膀装饰；整体点缀多彩五角星（黄/紫/红/绿/青/蓝/粉）与星光元素\",\n        \"size\": \"整体图案高度约28-32cm，宽度约22-26cm，占比胸前面积约60%\"\n      }\n    },\n    \"fabric_suggestion\": \"精梳棉平纹面料，宽松舒适版型，适合粉丝应援或日常穿搭\"\n  }\n}",
    imageUrl: "/images/case-04.png",
  },
  {
    id: 'case-02',
    category: "组织、社团、班级负责人",
    style: "管院科创：新中式商务休闲风",
    colors: {
      base: "蓝色polo",
      print: "白色印花",
      aux: "",
      raw: "蓝色polo+白色印花",
    },
    tags: ["简约文字（院训院徽）", "干净", "大气"],
    sizes: ["左胸前："],
    promptJson: "{\n  \"polo_tshirt_design\": {\n    \"style_type\": \"新中式商务休闲风\",\n    \"colors\": {\n      \"base_color\": \"湖蓝色/天蓝色\",\n      \"print_colors\": [\n        \"白色\"\n      ],\n      \"auxiliary_color\": \"白色（用于领口、袖口条纹装饰）\"\n    },\n    \"pattern_positions\": {\n      \"front\": {\n        \"location\": \"左胸位置（距离领口下方约12cm处）\",\n        \"content\": \"白色几何线条构成的“M”形品牌标识，两侧竖排文字“自信自强 自律至善”，下方搭配小号英文/拼音辅助文字\",\n        \"size\": \"整体图案高度约8-10cm，宽度约6-8cm\"\n      },\n      \"back\": {\n        \"location\": \"背部中心区域（覆盖肩胛骨下方至腰部以上）\",\n        \"content\": \"白色竖排书法字体，左侧为“自信自强”，右侧为“自律至善”，呈对称分布\",\n        \"size_ratio\": \"整体图案占背部面积约30%-40%\"\n      },\n      \"collar_and_sleeve\": {\n        \"location\": \"翻领领口及短袖袖口边缘\",\n        \"content\": \"双道白色细条纹装饰\",\n        \"description\": \"领口与袖口均采用两道平行白色条纹，增强运动感与精致感\"\n      }\n    }\n  }\n}",
    imageUrl: "/images/case-02.png",
  },
  {
    id: 'case-05',
    category: "电商平台搜索",
    style: "节日主题定制",
    colors: {
      base: "节日对应色系：圣诞：红",
      print: "绿",
      aux: "白",
      raw: "节日对应色系：圣诞：红 、绿、白",
    },
    tags: ["节庆", "欢乐", "温馨", "仪式感"],
    sizes: ["胸口图案：20–28cm"],
    promptJson: "{\n  \"christmas_sweater_design\": {\n    \"style_type\": \"清新趣味圣诞风\",\n    \"garment_type\": \"套头毛衣\",\n    \"colors\": {\n      \"base_color\": \"米白色\",\n      \"accent_colors\": [\n        \"圣诞红\",\n        \"松针绿\",\n        \"金色\",\n        \"暖橙色\"\n      ],\n      \"auxiliary_color\": \"深棕色\"\n    },\n    \"pattern_positions\": {\n      \"front\": {\n        \"location\": \"胸前中心区域（领口下方至腹部上方）\",\n        \"content\": \"苹果切片堆叠而成的圣诞树造型，顶部点缀金色星星与暖橙色蝴蝶结，苹果切片带有果核细节，周围散落金色星光点缀\",\n        \"size\": \"整体图案高度约25-30cm，宽度约18-22cm，占比胸前面积约55%\"\n      }\n    },\n    \"fabric_suggestion\": \"针织毛线面料，宽松休闲版型，柔软亲肤\"\n  }\n}",
    imageUrl: "/images/case-05.png",
  },
  {
    id: 'case-14',
    category: "校外商家需求",
    style: "剧本杀店：悬疑推理",
    colors: {
      base: "黑色polo",
      print: "亮蓝印花",
      aux: "橙",
      raw: "",
    },
    tags: ["设计感强", "风格多样", "传播力强"],
    sizes: ["正面LOGO位于左胸或中央名片大小", "背面正中央一句solgan（oversize版型）"],
    promptJson: "{\n  \"t_shirt_design\": {\n    \"theme\": \"剧本杀基础店服\",\n    \"style\": \"极简高街风\",\n    \"fit\": \"Oversize (宽松版型/落肩袖)\",\n    \"color_palette\": {\n      \"base_color\": \"碳黑色\",\n      \"print_color\": \"亮银色\"\n    },\n    \"front_details\": {\n      \"position\": \"左胸口\",\n      \"element_type\": \"Logo\",\n      \"content\": \"包含放大镜、钥匙、时钟元素的解谜主题图标及英文\",\n      \"size\": \"小巧精致（约名片大小）\"\n    },\n    \"back_details\": {\n      \"position\": \"后背上半部居中\",\n      \"element_type\": \"Slogan (标语)\",\n      \"content\": \"嘘, 天黑请闭眼\",\n      \"typography\": \"加粗无衬线字体 (黑体变体)\",\n      \"layout\": \"横向大字排版\"\n    }\n  }",
    imageUrl: "/images/case-14.png",
  },
  {
    id: 'case-06',
    category: "电商平台搜索",
    style: "宠物定制",
    colors: {
      base: "浅色系：白色",
      print: "米色",
      aux: "浅灰",
      raw: "浅色系：白色、米色、浅灰、浅蓝；辅助色：棕色、绿色",
    },
    tags: ["萌宠", "治愈", "情感表达"],
    sizes: ["胸口大图：30–35cm"],
    promptJson: "{\n  \"pet_design_clothing_design\": {\n    \"style_type\": \"治愈系宠物风\",\n    \"garment_type\": \"圆领长袖T恤（可延伸为卫衣/套头毛衣版型）\",\n    \"colors\": {\n      \"base_color\": \"纯白色\",\n      \"accent_colors\": [\n        \"浅奶咖色\",\n        \"暖棕色\",\n        \"粉米色\"\n      ],\n      \"auxiliary_color\": \"深棕色\"\n    },\n    \"pattern_positions\": {\n      \"front\": {\n        \"location\": \"胸前中心区域（领口下方至腹部上方）\",\n        \"content\": \"以图中浅米色小狗为主体的写实印花，包含小狗立耳、歪头、浅棕毛发与粉棕鼻头的特征，姿态温柔治愈，保留面部与前爪细节，整体风格柔和干净\",\n        \"size\": \"整体图案高度约22-26cm，宽度约16-20cm，占比胸前面积约50%\"\n      }\n    },\n    \"fabric_suggestion\": \"亲肤精梳棉面料，版型宽松舒适，适合日常休闲穿搭\"\n  }\n}",
    imageUrl: "/images/case-06.png",
  },
  {
    id: 'case-01',
    category: "组织、社团、班级负责人",
    style: "学促：新中式简约纪念风",
    colors: {
      base: "白色圆领T",
      print: "黑蓝白多色印花",
      aux: "",
      raw: "白色圆领T+黑蓝白多色印花",
    },
    tags: ["渐变晕染", "小标识", "组织名称", "设计感", "简约创意"],
    sizes: ["5cm*8cm 后背9cm*32cm"],
    promptJson: "{\n  \"tshirt_design\": {\n    \"style_type\": \"新中式简约纪念风\",\n    \"colors\": {\n      \"base_color\": \"纯白色\",\n      \"print_colors\": [\n        \"黑色\",\n        \"浅灰蓝/雾霾蓝\",\n        \"红色\",\n        \"深蓝色\"\n      ],\n      \"auxiliary_color\": \"无\"\n    },\n    \"pattern_positions\": {\n      \"front\": {\n        \"location\": \"左胸位置（距离领口下方约15cm处）\",\n        \"content\": \"深蓝色手写体“19th”文字，下方搭配黑色飞机剪影图案\",\n        \"size\": \"整体图案直径约6-8cm\"\n      },\n      \"back\": {\n        \"location\": \"背部中心区域（覆盖肩胛骨下方至腰部以上）\",\n        \"content\": \"大号书法字体“学促”，搭配水墨风格山水云雾与飞机剪影元素，右侧竖排小字“学生就业创业促进会”及红色标识点缀\",\n        \"size_ratio\": \"整体图案占背部面积约50%-60%\"\n      }\n    }\n  }\n}",
    imageUrl: "/images/case-01.png",
  },
  {
    id: 'case-03',
    category: "组织、社团、班级负责人",
    style: "西梦：公益社团活力风",
    colors: {
      base: "红色马甲",
      print: "黄色印花",
      aux: "",
      raw: "红色马甲+黄色印花",
    },
    tags: ["简洁明了"],
    sizes: ["胸前：6cm*7cm", "右臂：8cm*8cm 后背：27cm*28cm"],
    promptJson: "{\n  \"vest_design\": {\n    \"style_type\": \"公益社团活力风\",\n    \"colors\": {\n      \"base_color\": \"正红色\",\n      \"print_colors\": [\n        \"金黄色\"\n      ],\n      \"auxiliary_color\": \"银色（拉链装饰）\"\n    },\n    \"pattern_positions\": {\n      \"front\": {\n        \"location\": \"左胸位置（距离领口下方约10cm处）\",\n        \"content\": \"金黄色火焰/太阳造型的抽象图腾图标，下方搭配金黄色艺术字体“西部梦想”\",\n        \"size\": \"整体图案高度约8-10cm，宽度约6-8cm\"\n      },\n      \"back\": {\n        \"location\": \"背部中心区域（覆盖肩胛骨下方至腰部以上）\",\n        \"content\": \"顶部弧形排列金黄色英文“TKK WEST DREAM”，中间为大号金黄色卡通艺术字体“西部梦想”，底部为小号金黄色辅助文字（公益标语类内容）\",\n        \"size_ratio\": \"整体图案占背部面积约40%-50%\"\n      },\n      \"functional_details\": {\n        \"location\": \"正面衣身两侧\",\n        \"content\": \"对称式直插口袋设计\",\n        \"description\": \"正面左右各一个垂直长方形口袋，兼具实用性与视觉平衡感\"\n      }\n    }\n  }",
    imageUrl: "/images/case-03.png",
  },
  {
    id: 'case-07',
    category: "电商平台搜索",
    style: "京东：中大企业、政府（商务、极简）",
    colors: {
      base: "绝大部分： 黑",
      print: "白",
      aux: "藏青",
      raw: "绝大部分： 黑、白、藏青、花灰。不挑肤色、显瘦、且最容易凸显印花图案。\n高可见度/活动色： 大红、明黄、克莱因蓝、荧光绿。 此类颜色多用于户外拓展、大型展会、志愿者服务，主打“人群中一眼可见”。\n新兴趋势（高级感色彩）： 莫兰迪色系（如雾霾蓝、豆沙绿、燕麦色、大地色）",
    },
    tags: [],
    sizes: ["左胸标： 控制在 6cm - 10cm 之间", "前胸主图： 一般宽度在 20cm - 28cm（约A4纸宽度以内）", "后背大图： 宽度可达 28cm - 35cm"],
    promptJson: "{\n  \"apparel_details\": {\n    \"item_type\": \"短袖Polo衫 (翻领T恤/定制样机)\",\n    \"base_color\": \"藏青色 / 深蓝色 (Navy Blue)\",\n    \"design_style\": \"商务休闲 / 标准工服 (Business Casual / Uniform)\",\n    \"neckline\": \"翻领带门襟纽扣 (Polo Collar with Placket)\",\n    \"fit\": \"常规正肩版型\"\n  },\n  \"front_view\": {\n    \"pattern_distribution\": \"左胸印花位置提示\",\n    \"graphic_elements\": \"无复杂图形，仅占位符\",\n    \"text_content\": \"logo\",\n    \"text_position\": \"左胸 (Left Chest)\",\n    \"text_style\": \"白色小写无衬线英文字母\"\n  },\n  \"back_view\": {\n    \"pattern_distribution\": \"不可见，推测为纯色无印花\"\n  },\n  \"additional_info\": {\n    \"collar_details\": \"领口内侧可见白底蓝字方形领标\",\n    \"button_details\": \"门襟处可见两颗与衣服同色的纽扣\",\n    \"use_case_hint\": \"标准的B端企业或高规格团队服装定制占位图\"\n  }\n}",
    imageUrl: "/images/case-07.jpg",
  },
  {
    id: 'case-08',
    category: "电商平台搜索",
    style: "淘宝：学生团队、小微团队、年轻人（潮流、二次元、街头）",
    colors: {
      base: "白色",
      print: "靛蓝",
      aux: "淡蓝",
      raw: "",
    },
    tags: [],
    sizes: [],
    promptJson: "{\n  \"apparel_details\": {\n    \"item_type\": \"连帽夹克/风衣\",\n    \"base_color\": \"白色\",\n    \"design_style\": \"水彩晕染风 / 海洋主题\",\n    \"color_palette\": [\n      \"浅蓝色\",\n      \"蓝绿色\",\n      \"淡紫色\"\n    ]\n  },\n  \"front_view\": {\n    \"pattern_distribution\": \"水彩晕染主要分布在帽子、肩部、袖子及下摆两侧\",\n    \"graphic_elements\": \"拉链右侧有一群自上而下排布的小鲸鱼图案\"\n  },\n  \"back_view\": {\n    \"pattern_distribution\": \"背部中心有大面积水彩云朵状晕染背景\",\n    \"graphic_elements\": \"一只大鲸鱼穿过白色倒三角形边框的居中插画\",\n    \"text_content\": \"WE ARE FAMILY\",\n    \"text_style\": \"蓝色手写体，位于主图案右下方斜向排版\"\n  },\n  \"additional_info\": {\n    \"labels\": \"E86 (位于正反面展示图中间，可能是班级或款式编号)\"\n  }\n}",
    imageUrl: "/images/case-08.jpg",
  },
  {
    id: 'case-09',
    category: "电商平台搜索",
    style: "拼多多：餐饮商家、小商家、小型活动（简单、醒目、大字）\n4亚马逊：个人、特定爱好者（美式）",
    colors: {
      base: "深绿",
      print: "",
      aux: "",
      raw: "",
    },
    tags: [],
    sizes: [],
    promptJson: "{\n  \"apparel_details\": {\n    \"item_type\": \"短袖T恤 (基础打底衫/样机)\",\n    \"base_color\": \"墨绿色 / 深绿色 (Dark Green)\",\n    \"design_style\": \"纯色极简风 (Blank Canvas)\",\n    \"neckline\": \"圆领 (Crew Neck)\",\n    \"fit\": \"常规/正肩版型\"\n  },\n  \"front_view\": {\n    \"pattern_distribution\": \"无印花\",\n    \"graphic_elements\": \"无\",\n    \"text_content\": \"无\"\n  },\n  \"back_view\": {\n    \"pattern_distribution\": \"不可见，推测为纯色无印花\"\n  },\n  \"additional_info\": {\n    \"collar_details\": \"领口内侧可见红色矩形领标\",\n    \"image_context\": \"图片左侧边缘可见被截断的汉字“男”，推测原图为电商平台的“男款”或“男女同款”商品主图\"\n  }\n}",
    imageUrl: "/images/case-09.jpg",
  },
  {
    id: 'case-15',
    category: "校外商家需求",
    style: "独立设计师店：复古手工印花",
    colors: {
      base: "米白",
      print: "复古褐/墨绿",
      aux: "暗金",
      raw: "推荐使用天然染料与低饱和复古色系，避免高饱和荧光色。"
    },
    tags: ["复古", "手工", "独立设计", "小众"],
    sizes: ["胸前主图：20–24cm", "左袖小徽章：约5cm"],
    promptJson: "{\n  \"tshirt_design\": {\n    \"style_type\": \"复古手工印花（独立设计师店）\",\n    \"colors\": {\n      \"base_color\": \"米白/象牙白\",\n      \"print_colors\": [\"复古褐\", \"墨绿色\"],\n      \"auxiliary_color\": \"暗金\"\n    },\n    \"pattern_positions\": {\n      \"front\": {\n        \"location\": \"胸前中心（略偏上）\",\n        \"description\": \"手绘风格复古插画（植物与古董元素结合），模拟丝网印刷的颗粒感和轻微错位效果\",\n        \"size\": \"约20-24cm宽，高度根据比例调整\"\n      },\n      \"sleeve\": {\n        \"location\": \"左袖口小徽章\",\n        \"description\": \"缩小版品牌徽章或手写签名\",\n        \"size\": \"约5cm直径\"\n      }\n    },\n    \"fabric_suggestion\": \"中厚精梳棉或带纹理的天然棉布，适合手工印花\"\n  }\n}",
    imageUrl: "/images/case-15.png",
  },
  {
    id: 'case-16',
    category: "电商平台搜索",
    style: "复古手绘插画",
    colors: { base: "白", print: "深褐", aux: "焦糖", raw: "" },
    tags: ["插画", "复古", "手绘"],
    sizes: ["胸前：20-24cm"],
    promptJson: "{\n  \"note\": \"参考图片 case-16\"\n}",
    imageUrl: "/images/case-16.png",
  },
  {
    id: 'case-17',
    category: "电商平台搜索",
    style: "简约几何",
    colors: { base: "白", print: "靛蓝", aux: "浅灰", raw: "" },
    tags: ["极简", "几何"],
    sizes: ["胸前：15-22cm"],
    promptJson: "{\n  \"note\": \"参考图片 case-17\"\n}",
    imageUrl: "/images/case-17.png",
  },
  {
    id: 'case-18',
    category: "校外商家需求",
    style: "街头涂鸦风",
    colors: { base: "黑", print: "白/荧光", aux: "红", raw: "" },
    tags: ["街头", "涂鸦", "潮流"],
    sizes: ["正面主图：25-30cm"],
    promptJson: "{\n  \"note\": \"参考图片 case-18\"\n}",
    imageUrl: "/images/case-18.png",
  },
  {
    id: 'case-19',
    category: "电商平台搜索",
    style: "清新手绘",
    colors: { base: "米白", print: "薄荷绿", aux: "粉色", raw: "" },
    tags: ["手绘", "清新"],
    sizes: ["胸前：18-22cm"],
    promptJson: "{\n  \"note\": \"参考图片 case-19\"\n}",
    imageUrl: "/images/case-19.png",
  },
  {
    id: 'case-20',
    category: "电商平台搜索",
    style: "卡通可爱",
    colors: { base: "白", print: "亮黄", aux: "天蓝", raw: "" },
    tags: ["可爱", "卡通"],
    sizes: ["胸前：20-24cm"],
    promptJson: "{\n  \"note\": \"参考图片 case-20\"\n}",
    imageUrl: "/images/case-20.png",
  },
  {
    id: 'case-21',
    category: "校外商家需求",
    style: "极简标志",
    colors: { base: "浅灰", print: "深灰", aux: "白", raw: "" },
    tags: ["logo", "极简"],
    sizes: ["左胸：6-10cm"],
    promptJson: "{\n  \"note\": \"参考图片 case-21\"\n}",
    imageUrl: "/images/case-21.png",
  },
  {
    id: 'case-22',
    category: "电商平台搜索",
    style: "复古海报风",
    colors: { base: "奶白", print: "褐/墨绿", aux: "金色", raw: "" },
    tags: ["海报", "复古"],
    sizes: ["正面：22-28cm"],
    promptJson: "{\n  \"note\": \"参考图片 case-22\"\n}",
    imageUrl: "/images/case-22.png",
  },
  {
    id: 'case-23',
    category: "活动定制",
    style: "活力运动风",
    colors: { base: "亮蓝", print: "白", aux: "橙", raw: "" },
    tags: ["活动", "团队", "运动"],
    sizes: ["背部大图：25-30cm"],
    promptJson: "{\n  \"note\": \"参考图片 case-23\"\n}",
    imageUrl: "/images/case-23.png",
  },
  {
    id: 'case-26',
    category: "电商平台搜索",
    style: "现代艺术",
    colors: { base: "白", print: "多色", aux: "黑", raw: "" },
    tags: ["艺术", "抽象"],
    sizes: ["胸前：20-26cm"],
    promptJson: "{\n  \"note\": \"参考图片 case-26\"\n}",
    imageUrl: "/images/case-26.png",
  },
  {
    id: 'case-27',
    category: "校外商家需求",
    style: "怀旧拼贴",
    colors: { base: "米白", print: "棕色系", aux: "暗红", raw: "" },
    tags: ["怀旧", "拼贴"],
    sizes: ["正面：24-30cm"],
    promptJson: "{\n  \"note\": \"参考图片 case-27\"\n}",
    imageUrl: "/images/case-27.png",
  },
  {
    id: 'case-28',
    category: "电商平台搜索",
    style: "插画拼色",
    colors: { base: "浅灰", print: "粉蓝", aux: "黄", raw: "" },
    tags: ["插画", "色块"],
    sizes: ["胸前：18-22cm"],
    promptJson: "{\n  \"note\": \"参考图片 case-28\"\n}",
    imageUrl: "/images/case-28.png",
  },
  {
    id: 'case-29',
    category: "电商平台搜索",
    style: "抽象涂鸦",
    colors: { base: "黑", print: "白/红", aux: "黄", raw: "" },
    tags: ["抽象", "涂鸦"],
    sizes: ["胸前：20-25cm"],
    promptJson: "{\n  \"note\": \"参考图片 case-29\"\n}",
    imageUrl: "/images/case-29.png",
  },
  {
    id: 'case-30',
    category: "电商平台搜索",
    style: "潮流文字艺术",
    colors: { base: "白", print: "黑", aux: "亮色点缀", raw: "" },
    tags: ["文字", "潮流"],
    sizes: ["胸前：20-26cm"],
    promptJson: "{\n  \"note\": \"参考图片 case-30\"\n}",
    imageUrl: "/images/case-30.png",
  },
  {
    id: 'case-32',
    category: "活动定制",
    style: "学院风",
    colors: { base: "深蓝", print: "白", aux: "酒红", raw: "" },
    tags: ["学院", "简约"],
    sizes: ["左胸：6-10cm", "背部：20-28cm"],
    promptJson: "{\n  \"note\": \"参考图片 case-32\"\n}",
    imageUrl: "/images/case-32.png",
  },
  {
    id: 'case-33',
    category: "电商平台搜索",
    style: "手绘场景",
    colors: { base: "米白", print: "多色", aux: "灰", raw: "" },
    tags: ["场景", "手绘"],
    sizes: ["正面：22-28cm"],
    promptJson: "{\n  \"note\": \"参考图片 case-33\"\n}",
    imageUrl: "/images/case-33.png",
  },
  {
    id: 'case-34',
    category: "电商平台搜索",
    style: "极简线条",
    colors: { base: "白", print: "黑", aux: "灰", raw: "" },
    tags: ["线条", "极简"],
    sizes: ["胸前：15-20cm"],
    promptJson: "{\n  \"note\": \"参考图片 case-34\"\n}",
    imageUrl: "/images/case-34.png",
  },
  {
    id: 'case-35',
    category: "活动定制",
    style: "马赛克拼贴",
    colors: { base: "黑", print: "彩色", aux: "白", raw: "" },
    tags: ["拼贴", "创意"],
    sizes: ["正面：24-30cm"],
    promptJson: "{\n  \"note\": \"参考图片 case-35\"\n}",
    imageUrl: "/images/case-35.png",
  },
  {
    id: 'case-36',
    category: "电商平台搜索",
    style: "卡通场景",
    colors: { base: "白", print: "多色", aux: "亮色", raw: "" },
    tags: ["卡通", "场景"],
    sizes: ["胸前：20-26cm"],
    promptJson: "{\n  \"note\": \"参考图片 case-36\"\n}",
    imageUrl: "/images/case-36.png",
  },
];
